require('autocommands/common')
require('base/common')
require('base/mappings')
require('base/search')
require('base/tabs')
require('commands/format')
require('commands/other')
require('plugins/init')
